# SwiftLint Configuration for HelioCentric Mood

# Paths to include/exclude
included:
  - HelioCentricMood
  - Shared
  - Features
  - Tests

excluded:
  - Pods
  - .build
  - DerivedData

# Rules to enable/disable
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: '!\s*$'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping. Use safe unwrapping instead."
    severity: warning

  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print statements."
    severity: warning

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration
