name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --reporter github
      
    - name: Build project
      run: |
        xcodebuild build \
          -workspace HelioCentricMood.xcworkspace \
          -scheme HelioCentricMood \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' \
          -configuration Debug
          
    - name: Run unit tests
      run: |
        xcodebuild test \
          -workspace HelioCentricMood.xcworkspace \
          -scheme HelioCentricMood \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' \
          -configuration Debug
          
    - name: Run UI tests
      run: |
        xcodebuild test \
          -workspace HelioCentricMood.xcworkspace \
          -scheme HelioCentricMood \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max' \
          -configuration Debug \
          -only-testing:HelioCentricMoodUITests
